/**
 * Severity level of an alert generated by the system.
 */
public enum SeverityLevel {
    WARNING("Warning - value approaching threshold"),
    CRITICAL("Critical - value exceeded threshold");

    private final String description;

    SeverityLevel(String description) {
        this.description = description;
    }

    public String getDescription() { return description; }
}
